name: loggy_dio
description: Extension for loggy. Includes interactor and pretty printer for Dio.
version: 0.0.1
repository: https://github.com/infinum/flutter-logger
homepage: https://github.com/infinum/flutter-logger

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  loggy:
    path: ../loggy
  dio: ^4.0.0
